# Generated by Django 5.2.4 on 2025-07-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_download_link_book_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='formats/'),
        ),
        migrations.AlterField(
            model_name='format',
            name='mime_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('docx', 'DOCX'), ('epub', 'EPUB')], max_length=100),
        ),
    ]
