# Generated by Django 5.2.4 on 2025-07-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_format_uploaded_file_alter_format_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='mime_type',
            field=models.CharField(choices=[('application/pdf', 'PDF'), ('text/plain', 'Text'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'DOCX'), ('application/epub+zip', 'EPUB')], max_length=100),
        ),
    ]
