# Generated by Django 5.2.4 on 2025-07-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_format_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
